version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
#    volumes:
#      - ./mongo/data/db:/data/db
  server:
    build: ./server
#    ports:
#      - "4000:4000"
    environment:
      - MONGO=mongodb://mongo:27017
    links:
      - mongo:mongo
  store:
    build: ./server
    #    ports:
    #      - "4000:4000"
    environment:
      - MONGO=mongodb://mongo:27017
      - BAIDU_AIP_APP_ID=
      - BAIDU_AIP_API_KEY=
      - BAIDU_AIP_SECRET_KEY=
      - STORE=1
    links:
      - mongo:mongo
  spider:
    build: ./spider
    environment:
      - API_URL=http://server:4000/graphql
    links:
      - server:server
  web:
    build:
      context: ./web
      args:
        REACT_APP_API_URL: http://192.168.43.211:4000/graphql
        REACT_APP_WEBSOCKET_URL: ws://192.168.43.211:4000/graphql
    environment:
      - REACT_APP_API_URL=http://192.168.43.211:5000/graphql
      - REACT_APP_WEBSOCKET_URL=ws://192.168.43.211:5000/graphql
#    ports:
#      - "3000:3000"
  nginx:
    build: ./nginx
    links:
      - server:server
      - web:web
    ports:
      - "5000:80"